### ISSUE TITLE
transcode error

### ISSUE THREAD

**Issue by zsozso** [segator/proxylive#1]
Hi,

I tried to use proxylive without success. I've got this message run proxylive in MacOS Docker:

> Input #0, mpegts, from 'http://xxxxxxx:9981/stream/channel/bbf9b26ed82ad77c53142a775e2dbb98':
  Duration: N/A, start: 20319.848100, bitrate: N/A
  Program 303 
    Metadata:
      service_name    : Nat Geo HD
      service_provider: DIGI Videk
    Stream #0:0[0x1f40]: Video: h264 ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, top first), 1920x1080 [SAR 1:1 DAR 16:9], 25 fps, 50 tbr, 90k tbn, 50 tbc
    Stream #0:1[0x1f41](hun): Audio: mp2 ([4][0][0][0] / 0x0004), 48000 Hz, stereo, s16p, 192 kb/s
Output #0, mpegts, to 'pipe:':
  Metadata:
    encoder         : Lavf57.56.100
    Stream #0:0: Video: h264 ([27][0][0][0] / 0x001B), yuv420p(tv, bt709, top first), 1920x1080 [SAR 1:1 DAR 16:9], q=2-31, 25 fps, 50 tbr, 90k tbn, 90k tbc
    Stream #0:1(hun): Audio: mp2 ([4][0][0][0] / 0x0004), 48000 Hz, stereo, 192 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (copy)
  Stream #0:1 -> #0:1 (copy)
Press [q] to stop, [?] for help
stopping from controller
[bbf9b26ed82ad77c53142a775e2dbb98_raw] Required Terminate Transcode
Saliendo Error Thread
que pasa dudeeeeeeeeeeeeee
LOL1
[bbf9b26ed82ad77c53142a775e2dbb98_raw] Terminated Transcode
User Close:{ip=172.17.0.1, browserInfo=Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/602.4.8 (KHTML, like Gecko) Version/10.0.3 Safari/602.4.8, streams=]}

**Comment by segator** [comment]
it seems your client is closing connection

[bbf9b26ed82ad77c53142a775e2dbb98_raw] Required Terminate Transcode
Sorry to this weird log messages, I should clean up the logs.

**Comment by segator** [comment]
any new?
