### ISSUE TITLE
Application wont launch

### ISSUE THREAD

**Issue by Ermess94** [segator/proxylive#10]
Hi there!
I'm struggling in trying to launch the application, I've successfully built the app but when I attempt to launch it using "java -jar proxylive.jar" command, it throws some exceptions relatively beans creation, it looks like there are some unsatisfied dependencies.
Can you figure out what's the problem?

I'm going to attach the log details.

[log details.txt](https://github.com/segator/proxylive/files/4025904/log.details.txt)

**Comment by segator** [comment]
Same as #11
