### ISSUE TITLE
Error on transcoding

### ISSUE THREAD

**Issue by satis4action** [segator/proxylive#14]
sorry, it's me again, after server starts without any issus (see issue #13) using link faced issue below, could you please help again

http://IP:8080/view/480p/9f3aaf85a39f3b5441e7e8ff537832ca/playlist.m3u8?user=null&pass=null 
'
------------------------------error begin-----------------------------------
ERROR [9f3aaf85a39f3b5441e7e8ff537832ca_480p] com.github.segator.proxylive.tasks.DirectTranscodeTask: Error on transcoding 9f3aaf85a39f3b5441e7e8ff537832ca_480p
java.io.IOException: Process is not running
        at com.github.segator.proxylive.tasks.DirectTranscodeTask.isRunning(DirectTranscodeTask.java:228)
        at com.github.segator.proxylive.tasks.DirectTranscodeTask.run(DirectTranscodeTask.java:146)
        at java.base/java.lang.Thread.run(Thread.java:834)

-----------------------------------error end----------------------------------------------------------------
'
system is:
ffmpeg version 4.1.4-1~deb10u1 Copyright (c) 2000-2019 the FFmpeg developers
built with gcc 8 (Debian 8.3.0-6)
configuration: --prefix=/usr --extra-version='1~deb10u1' --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
libavutil      56. 22.100 / 56. 22.100
libavcodec     58. 35.100 / 58. 35.100
libavformat    58. 20.100 / 58. 20.100
libavdevice    58.  5.100 / 58.  5.100
libavfilter     7. 40.101 /  7. 40.101
libavresample   4.  0.  0 /  4.  0.  0
libswscale      5.  3.100 /  5.  3.100
libswresample   3.  3.100 /  3.  3.100
libpostproc    55.  3.100 / 55.  3.100

**Comment by satis4action** [comment]
all fine, working ok. i had cofused again with configuration file... sorry

**Comment by segator** [comment]
So now it's working? cool :)

let me now if you need any further help

**Comment by alturismo** [comment]
may i also ask what solved your issue, i run in the same issue here and cant really find what i did wrong

tvheadend backend setup, seems also the playlist generating fine, here a entry from the proxylive playlist as sample

`#EXTM3U cache=2000 url-tvg="http://192.168.1.64:8080/epg" x-tvg-url="http://192.168.1.64:8080/epg" tvg-shift=0

#EXTINF:-1 tvg-chno="10"   group-title="HDTV"  tvg-id="c0c7287a8b7ea27d7c268d2005ccc2cf" tvg-name="Das Erste HD" type="hls",Das Erste HD
http://192.168.1.64:8080/view/1080p/c0c7287a8b7ea27d7c268d2005ccc2cf/playlist.m3u8?user=null&pass=null
#EXTINF:-1 tvg-chno="15"   group-title="HDTV"  tvg-id="173e5acdd481079ac918410e2d00ba31" tvg-name="ZDF HD" type="hls",ZDF HD
http://192.168.1.64:8080/view/1080p/173e5acdd481079ac918410e2d00ba31/playlist.m3u8?user=null&pass=null`

i fetch the lists like this
http://192.168.1.64:8080/channel/list/hls/1080p
http://192.168.1.64:8080/channel/list/mpeg/1080p

but result is always some transcoding errors, sample from logs ...

`[30m2020-10-06 11:17:32,958[0;39m [1;31mERROR[0;39m [[34mTranscoding Error Reader Thread:4b8df1ff3935810698e38a335719a1ca_1080p[0;39m] [33mcom.github.segator.proxylive.tasks.DirectTranscodeTask$1[0;39m: [4b8df1ff3935810698e38a335719a1ca_1080p] Error on transcoding

java.io.IOException: Process is not running
at com.github.segator.proxylive.tasks.DirectTranscodeTask.isRunning(DirectTranscodeTask.java:228)
at com.github.segator.proxylive.tasks.DirectTranscodeTask$1.run(DirectTranscodeTask.java:117)
[30m2020-10-06 11:17:32,958[0;39m [39mDEBUG[0;39m [[34m4b8df1ff3935810698e38a335719a1ca_1080p[0;39m] [33mcom.github.segator.proxylive.tasks.DirectTranscodeTask[0;39m: [4b8df1ff3935810698e38a335719a1ca_1080p] Start Transcode
[30m2020-10-06 11:17:32,958[0;39m [39mDEBUG[0;39m [[34m4b8df1ff3935810698e38a335719a1ca_1080p[0;39m] [33mcom.github.segator.proxylive.tasks.DirectTranscodeTask[0;39m: [4b8df1ff3935810698e38a335719a1ca_1080p] Transcoding Command: /usr/local/bin/ffmpeg -sn -c:a:0 aac -ac 2 -b:a 320k
-c:v libx264 -tune zerolatency -g 300 -vprofile high
-level 4.0 -movflags +faststart -bufsize 15000k
-maxrate 5000k -preset faster -vf yadif=0 -threads 0 -f mpegts
-mpegts_m2ts_mode 1 -mpegts_copyts 1
-mpegts_flags +resend_headers -
[30m2020-10-06 11:17:32,974[0;39m [1;31mERROR[0;39m [[34m4b8df1ff3935810698e38a335719a1ca_1080p[0;39m] [33mcom.github.segator.proxylive.tasks.DirectTranscodeTask[0;39m: Error on transcoding 4b8df1ff3935810698e38a335719a1ca_1080p

java.io.IOException: Process is not running`

and here my application.yml

`---
geoIP:
    enabled: false
source:
    reconnectTimeout: 10
    tvheadendURL: http://user:pass@192.168.1.77:9981
    channels:
        type: tvheadend
        refresh: 86400 #In seconds
    epg:
        url: http://user:pass@192.168.1.77:9981/xmltv/channels
        refresh: 86400
ffmpeg:
    path: '/usr/local/bin/ffmpeg'

    profiles:
        -
            alias: "aac"
            parameters: "-sn -ac 2 -c:a aac -b:a 320k -c:v copy"
        -
            alias: "240p"
            parameters: "-sn -c:a:0 aac \n
            -ac 2 -b:a 64k -c:v libx264 \n
            -tune zerolatency -g 10 -vprofile \n
            high -level 4.0 -crf 18 -movflags +faststart \n
            -bufsize 15000k -maxrate 300k  -preset veryslow \n
            -vf scale=-1:244,yadif=0"
        -
            alias: "360p"
            parameters: "-sn -c:a:0 aac \n
            -ac 2 -b:a 96k -c:v libx264 \n
            -tune zerolatency -g 10 -vprofile \n
            high -level 4.0 -crf 18 -movflags +faststart \n
            -bufsize 15000k -maxrate 700k  -preset veryslow \n
            -vf scale=-1:360,yadif=0"
        -
            alias: "480p"
            parameters: "-sn -c:a:0 aac -ac 2 -b:a 196k -c:v libx264 \n
            -tune zerolatency -g 10 -vprofile high -level 4.0 \n
            -crf 18 -movflags +faststart -bufsize 15000k \n
            -maxrate 1500k  -preset slow -vf scale=-1:484,yadif=0"
        -
            alias: "720p"
            parameters: "-sn  -c:a:0 aac -ac 2 -b:a 320k \n
            -c:v libx264 -tune zerolatency \n
            -g 10 -vprofile high -level 4.0 -crf 18 \n
            -movflags +faststart -bufsize 15000k \n
            -maxrate 3000k  -preset fast -vf scale=-1:720,yadif=0"
        -
            alias: "1080p"
            parameters: "-sn  -c:a:0 aac -ac 2 -b:a 320k \n
            -c:v libx264 -tune zerolatency -g 300 -vprofile high \n
            -level 4.0 -movflags +faststart -bufsize 15000k \n
            -maxrate 5000k  -preset faster -vf yadif=0"
    mpegTS:
        parameters: "-threads 0 -f mpegts \n
        -mpegts_m2ts_mode 1 -mpegts_copyts 1 \n
        -mpegts_flags +resend_headers  "
    hls:
        enabled: true
        tempPath: "/tmp"
        parameters: "-flags -global_header  -avoid_negative_ts disabled \n
        -map_metadata -1 -start_at_zero -copyts -flags -global_header \n
        -vsync cfr -y -nostats -f hls  -hls_time 2 -hls_list_size 10 \n
        -hls_wrap 20 -hls_allow_cache 0  -hls_flags +append_list \n
        -hls_flags +discont_start -hls_flags +delete_segments"
        timeout: 30

buffers:
    chunkSize: 1048576
    broadcastBufferSize: 52428800`

ffmpeg output from docker

`ffmpeg version 3.4.8 Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)
  configuration: --disable-debug --disable-doc --disable-ffplay --enable-shared --enable-avresample --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-gpl --enable-libass --enable-fontconfig --enable-libfreetype --enable-libvidstab --enable-libmp3lame --enable-libopus --enable-libtheora --enable-libvorbis --enable-libvpx --enable-libwebp --enable-libxcb --enable-libx265 --enable-libxvid --enable-libx264 --enable-nonfree --enable-openssl --enable-libfdk_aac --enable-postproc --enable-small --enable-version3 --enable-libbluray --enable-libzmq --extra-libs=-ldl --prefix=/opt/ffmpeg --enable-libopenjpeg --enable-libkvazaar --enable-vaapi --extra-cflags=-I/opt/ffmpeg/include --extra-ldflags=-L/opt/ffmpeg/lib
  libavutil      55. 78.100 / 55. 78.100
  libavcodec     57.107.100 / 57.107.100
  libavformat    57. 83.100 / 57. 83.100
  libavdevice    57. 10.100 / 57. 10.100
  libavfilter     6.107.100 /  6.107.100
  libavresample   3.  7.  0 /  3.  7.  0
  libswscale      4.  8.100 /  4.  8.100
  libswresample   2.  9.100 /  2.  9.100
  libpostproc    54.  7.100 / 54.  7.100`

may an idea what im doing wrong ?

**Comment by segator** [comment]
Seems ffmpeg is crashing with your encoding parameters, why are you adding \ n? maybe this is causing the issue?

**Comment by alturismo** [comment]
was one from a "working" paste for this configuration file ...

im testng now through howto resolve this, but basically there is no working sample here it seems (for my usecase actually)

i fetched now from the readme step by step, added as extra

geoIP:
    enabled: false

modified ffmpeg path for docker

so far mpeg playlists are playing, but with alot of errors

sample
`[30m2020-10-06 12:31:30,733[0;39m [39mDEBUG[0;39m [[34mTranscoding Error Reader Thread:f0ae2f2a7674d56a85e536e5a7c7b00b_720p[0;39m] [33mcom.github.segator.proxylive.tasks.DirectTranscodeTask$1[0;39m: [f0ae2f2a7674d56a85e536e5a7c7b00b_720p] frame= 616 fps= 25 q=24.0 size= 12205kB time=00:00:26.64 bitrate=3753.2kbits/s speed=1.09x

[30m2020-10-06 12:31:31,333[0;39m [39mDEBUG[0;39m [[34mTranscoding Error Reader Thread:f0ae2f2a7674d56a85e536e5a7c7b00b_720p[0;39m] [33mcom.github.segator.proxylive.tasks.DirectTranscodeTask$1[0;39m: [f0ae2f2a7674d56a85e536e5a7c7b00b_720p] frame= 635 fps= 25 q=24.0 size= 12563kB time=00:00:27.40 bitrate=3756.0kbits/s speed= 1.1x

[30m2020-10-06 12:31:31,734[0;39m [39mDEBUG[0;39m [[34mTranscoding Error Reader Thread:f0ae2f2a7674d56a85e536e5a7c7b00b_720p[0;39m] [33mcom.github.segator.proxylive.tasks.DirectTranscodeTask$1[0;39m: [f0ae2f2a7674d56a85e536e5a7c7b00b_720p] frame= 652 fps= 26 q=24.0 size= 12915kB time=00:00:28.08 bitrate=3767.7kbits/s speed= 1.1x

[30m2020-10-06 12:31:31,789[0;39m [39mDEBUG[0;39m [[34mhttp-nio-8080-exec-4[0;39m] [33mcom.github.segator.proxylive.tasks.DirectTranscodeTask[0;39m: [f0ae2f2a7674d56a85e536e5a7c7b00b_720p] Required Terminate Transcode
[30m2020-10-06 12:31:31,934[0;39m [39mDEBUG[0;39m [[34mf0ae2f2a7674d56a85e536e5a7c7b00b_720p[0;39m] [33mcom.github.segator.proxylive.tasks.DirectTranscodeTask[0;39m: [f0ae2f2a7674d56a85e536e5a7c7b00b_720p] Terminated Transcode
[30m2020-10-06 12:31:31,934[0;39m [39mDEBUG[0;39m [[34mhttp-nio-8080-exec-4[0;39m] [33mcom.github.segator.proxylive.controller.StreamController[0;39m: Close Stream f0ae2f2a7674d56a85e536e5a7c7b00b by guest

[30m2020-10-06 12:31:31,946[0;39m [39mDEBUG[0;39m [[34mhttp-nio-8080-exec-1[0;39m] [33mcom.github.segator.proxylive.controller.StreamController[0;39m: Close Stream f0ae2f2a7674d56a85e536e5a7c7b00b by internal`

hls also working, also alot off errors
`[30m2020-10-06 12:36:23,353[0;39m [39mDEBUG[0;39m [[34mf0ae2f2a7674d56a85e536e5a7c7b00b_1080p_HLS[0;39m] [33mcom.github.segator.proxylive.tasks.HLSDirectTask[0;39m: [f0ae2f2a7674d56a85e536e5a7c7b00b_1080p_HLS] [hls @ 0x562691e23140] Opening '/tmp/f0ae2f2a7674d56a85e536e5a7c7b00b_1080p_HLS/playlist0.ts' for writing
[30m2020-10-06 12:36:23,353[0;39m [39mDEBUG[0;39m [[34mf0ae2f2a7674d56a85e536e5a7c7b00b_1080p_HLS[0;39m] [33mcom.github.segator.proxylive.tasks.HLSDirectTask[0;39m: [f0ae2f2a7674d56a85e536e5a7c7b00b_1080p_HLS] [hls @ 0x562691e23140] Opening '/tmp/f0ae2f2a7674d56a85e536e5a7c7b00b_1080p_HLS/playlist.m3u8.tmp' for writing
[30m2020-10-06 12:36:23,510[0;39m [39mDEBUG[0;39m [[34mTranscoding Error Reader Thread:f0ae2f2a7674d56a85e536e5a7c7b00b_1080p[0;39m] [33mcom.github.segator.proxylive.tasks.DirectTranscodeTask$1[0;39m: [f0ae2f2a7674d56a85e536e5a7c7b00b_1080p] frame= 1076 fps= 21 q=24.0 size= 30490kB time=00:00:43.92 bitrate=5687.1kbits/s speed=0.852x

[30m2020-10-06 12:36:23,911[0;39m [39mDEBUG[0;39m [[34mTranscoding Error Reader Thread:f0ae2f2a7674d56a85e536e5a7c7b00b_1080p[0;39m] [33mcom.github.segator.proxylive.tasks.DirectTranscodeTask$1[0;39m: [f0ae2f2a7674d56a85e536e5a7c7b00b_1080p] frame= 1087 fps= 21 q=24.0 size= 30956kB time=00:00:44.36 bitrate=5716.7kbits/s speed=0.852x

[30m2020-10-06 12:36:24,511[0;39m [39mDEBUG[0;39m [[34mTranscoding Error Reader Thread:f0ae2f2a7674d56a85e536e5a7c7b00b_1080p[0;39m] [33mcom.github.segator.proxylive.tasks.DirectTranscodeTask$1[0;39m: [f0ae2f2a7674d56a85e536e5a7c7b00b_1080p] frame= 1101 fps= 21 q=24.0 size= 31318kB time=00:00:44.92 bitrate=5711.5kbits/s speed=0.855x

[30m2020-10-06 12:36:24,693[0;39m [39mDEBUG[0;39m [[34mf0ae2f2a7674d56a85e536e5a7c7b00b_1080p_HLS[0;39m] [33mcom.github.segator.proxylive.tasks.HLSDirectTask[0;39m: [f0ae2f2a7674d56a85e536e5a7c7b00b_1080p_HLS] [hls @ 0x562691e23140] Opening '/tmp/f0ae2f2a7674d56a85e536e5a7c7b00b_1080p_HLS/playlist1.ts' for writing
[30m2020-10-06 12:36:24,693[0;39m [39mDEBUG[0;39m [[34mf0ae2f2a7674d56a85e536e5a7c7b00b_1080p_HLS[0;39m] [33mcom.github.segator.proxylive.tasks.HLSDirectTask[0;39m: [f0ae2f2a7674d56a85e536e5a7c7b00b_1080p_HLS] [hls @ 0x562691e23140] Opening '/tmp/f0ae2f2a7674d56a85e536e5a7c7b00b_1080p_HLS/playlist.m3u8.tmp' for writing
[30m2020-10-06 12:36:25,112[0;39m [39mDEBUG[0;39m [[34mTranscoding Error Reader Thread:f0ae2f2a7674d56a85e536e5a7c7b00b_1080p[0;39m] [33mcom.github.segator.proxylive.tasks.DirectTranscodeTask$1[0;39m: [f0ae2f2a7674d56a85e536e5a7c7b00b_1080p] frame= 1114 fps= 21 q=26.0 size= 31710kB time=00:00:45.44 bitrate=5716.7kbits/s speed=0.856x

[30m2020-10-06 12:36:25,512[0;39m [39mDEBUG[0;39m [[34mTranscoding Error Reader Thread:f0ae2f2a7674d56a85e536e5a7c7b00b_1080p[0;39m] [33mcom.github.segator.proxylive.tasks.DirectTranscodeTask$1[0;39m: [f0ae2f2a7674d56a85e536e5a7c7b00b_1080p] frame= 1125 fps= 21 q=26.0 size= 31940kB time=00:00:45.88 bitrate=5702.9kbits/s speed=0.856x

[30m2020-10-06 12:36:26,115[0;39m [39mDEBUG[0;39m [[34mTranscoding Error Reader Thread:f0ae2f2a7674d56a85e536e5a7c7b00b_1080p[0;39m] [33mcom.github.segator.proxylive.tasks.DirectTranscodeTask$1[0;39m: [f0ae2f2a7674d56a85e536e5a7c7b00b_1080p] frame= 1137 fps= 21 q=27.0 size= 32446kB time=00:00:46.36 bitrate=5733.3kbits/s speed=0.856x

[30m2020-10-06 12:36:26,716[0;39m [39mDEBUG[0;39m [[34mTranscoding Error Reader Thread:f0ae2f2a7674d56a85e536e5a7c7b00b_1080p[0;39m] [33mcom.github.segator.proxylive.tasks.DirectTranscodeTask$1[0;39m: [f0ae2f2a7674d56a85e536e5a7c7b00b_1080p] frame= 1148 fps= 21 q=27.0 size= 32856kB time=00:00:46.80 bitrate=5751.2kbits/s speed=0.856x

[30m2020-10-06 12:36:27,116[0;39m [39mDEBUG[0;39m [[34mTranscoding Error Reader Thread:f0ae2f2a7674d56a85e536e5a7c7b00b_1080p[0;39m] [33mcom.github.segator.proxylive.tasks.DirectTranscodeTask$1[0;39m: [f0ae2f2a7674d56a85e536e5a7c7b00b_1080p] frame= 1156 fps= 21 q=27.0 size= 33165kB time=00:00:47.12 bitrate=5765.9kbits/s speed=0.854x

[30m2020-10-06 12:36:27,717[0;39m [39mDEBUG[0;39m [[34mTranscoding Error Reader Thread:f0ae2f2a7674d56a85e536e5a7c7b00b_1080p[0;39m] [33mcom.github.segator.proxylive.tasks.DirectTranscodeTask$1[0;39m: [f0ae2f2a7674d56a85e536e5a7c7b00b_1080p] frame= 1164 fps= 21 q=28.0 size= 33352kB time=00:00:47.44 bitrate=5759.3kbits/s speed=0.852x

[30m2020-10-06 12:36:28,117[0;39m [39mDEBUG[0;39m [[34mTranscoding Error Reader Thread:f0ae2f2a7674d56a85e536e5a7c7b00b_1080p[0;39m] [33mcom.github.segator.proxylive.tasks.DirectTranscodeTask$1[0;39m: [f0ae2f2a7674d56a85e536e5a7c7b00b_1080p] frame= 1174 fps= 21 q=28.0 size= 33699kB time=00:00:47.84 bitrate=5770.6kbits/s speed=0.851x

[30m2020-10-06 12:36:28,286[0;39m [39mDEBUG[0;39m [[34mf0ae2f2a7674d56a85e536e5a7c7b00b_1080p_HLS[0;39m] [33mcom.github.segator.proxylive.tasks.HLSDirectTask[0;39m: [f0ae2f2a7674d56a85e536e5a7c7b00b_1080p_HLS] [hls @ 0x562691e23140] Opening '/tmp/f0ae2f2a7674d56a85e536e5a7c7b00b_1080p_HLS/playlist2.ts' for writing
[30m2020-10-06 12:36:28,286[0;39m [39mDEBUG[0;39m [[34mf0ae2f2a7674d56a85e536e5a7c7b00b_1080p_HLS[0;39m] [33mcom.github.segator.proxylive.tasks.HLSDirectTask[0;39m: [f0ae2f2a7674d56a85e536e5a7c7b00b_1080p_HLS] [hls @ 0x562691e23140] Opening '/tmp/f0ae2f2a7674d56a85e536e5a7c7b00b_1080p_HLS/playlist.m3u8.tmp' for writing
[30m2020-10-06 12:36:28,717[0;39m [39mDEBUG[0;39m [[34mTranscoding Error Reader Thread:f0ae2f2a7674d56a85e536e5a7c7b00b_1080p[0;39m] [33mcom.github.segator.proxylive.tasks.DirectTranscodeTask$1[0;39m: [f0ae2f2a7674d56a85e536e5a7c7b00b_1080p] frame= 1186 fps= 21 q=26.0 size= 33977kB time=00:00:48.32 bitrate=5760.4kbits/s speed=0.852x

[30m2020-10-06 12:36:28,794[0;39m [39mDEBUG[0;39m [[34mscheduling-1[0;39m] [33mcom.github.segator.proxylive.tasks.HLSDirectTask[0;39m: [f0ae2f2a7674d56a85e536e5a7c7b00b_1080p_HLS] Required Terminate HLS
[30m2020-10-06 12:36:28,799[0;39m [39mDEBUG[0;39m [[34mf0ae2f2a7674d56a85e536e5a7c7b00b_1080p_HLS[0;39m] [33mcom.github.segator.proxylive.tasks.HLSDirectTask[0;39m: [f0ae2f2a7674d56a85e536e5a7c7b00b_1080p_HLS] Terminated HLS
[30m2020-10-06 12:36:28,860[0;39m [39mDEBUG[0;39m [[34mhttp-nio-8080-exec-3[0;39m] [33mcom.github.segator.proxylive.tasks.DirectTranscodeTask[0;39m: [f0ae2f2a7674d56a85e536e5a7c7b00b_1080p] Required Terminate Transcode
[30m2020-10-06 12:36:28,918[0;39m [39mDEBUG[0;39m [[34mf0ae2f2a7674d56a85e536e5a7c7b00b_1080p[0;39m] [33mcom.github.segator.proxylive.tasks.DirectTranscodeTask[0;39m: [f0ae2f2a7674d56a85e536e5a7c7b00b_1080p] Terminated Transcode
[30m2020-10-06 12:36:28,918[0;39m [39mDEBUG[0;39m [[34mhttp-nio-8080-exec-3[0;39m] [33mcom.github.segator.proxylive.controller.StreamController[0;39m: Close Stream f0ae2f2a7674d56a85e536e5a7c7b00b by internal

[30m2020-10-06 12:36:29,116[0;39m [39mDEBUG[0;39m [[34mhttp-nio-8080-exec-5[0;39m] [33mcom.github.segator.proxylive.controller.StreamController[0;39m: Close Stream f0ae2f2a7674d56a85e536e5a7c7b00b by internal`

and, looks like no hw accelartion (vaapi) is used, very high cpu usage ... so i guess those errors come from there someway

**Comment by segator** [comment]
interesting, send me somehow a  file with some minutes of streaming to see why is failing and i can help you. and about vaapi you need to adapt your ffmpeg command as is like a diferent video encoder. you also have an example of vaapi on the page. also remember if you using docker you need to add the device to the docker.

**Comment by alturismo** [comment]
device is of course added, ;) i use tvheadend, plex, emby, even ubuntu in docker with vaapi support and working.

already tried to look for the command strings, i ll invest further and look deeper in your command string, my point is, hls ...
normal encoding im fine, im just looking for the hls feature and there im absolutely not common howto use it with ffmpeg ;)

from docker shell about /dev/dri looking good as expected
`
# ls -la /dev/dri
total 0
drwxr-xr-x  2 root root        80 Oct  6 11:34 .
drwxr-xr-x 13 root root      3280 Oct  6 11:34 ..
crw-rw----  1 root    18 226,   0 Oct  6 11:34 card0
crwxrwxrwx  1   99 users 226, 128 Oct  6 11:34 renderD128
#
 `

attached a small snipp of recording, mainly 1080i/50 processed here, if you have a suggestion, thanks ahead ;)

[Navy CIS_ L.A - S01E10 - Die Last der Schuld.ts.zip](https://github.com/segator/proxylive/files/5334321/Navy.CIS_.L.A.-.S01E10.-.Die.Last.der.Schuld.ts.zip)

**Comment by alturismo** [comment]
little update, using

alias: "vaapi1080p"
parameters: "-hwaccel vaapi -vaapi_device /dev/dri/renderD128 -hwaccel_output_format vaapi -i {input} {channelParameters} -sn  -c:a:0 aac -ac 2 -b:a 320k -c:v h264_vaapi -tune zerolatency -g 300 -level 41 -movflags +faststart -bufsize 15000k -maxrate 5000k  -preset faster -vf format=vaapi,hwupload,deinterlace_vaapi"

will work to transcode hw accelerated mpeg 1080p, hls vaapi1080p is not working at all then, just as note, stalling cpu but no output.

**Comment by alturismo** [comment]
small update after playing inside docker cli

sample
ffmpeg -hwaccel vaapi -vaapi_device /dev/dri/renderD128 -hwaccel_output_format vaapi -i http://192.168.1.77:9981/stream/channelid/707768048?auth=myauthhere -sn -c:a:0 aac -ac 2 -b:a 320k -c:v h264_vaapi -tune zerolatency -g 10 -level 4.0 -crf 18 -movflags +faststart -bufsize 15000k -maxrate 2000k -preset faster -vf format=vaapi,hwupload,deinterlace_vaapi -threads 0 -f mpegts -mpegts_m2ts_mode 1 -mpegts_copyts 1 -mpegts_flags +resend_headers -hide_banner -f hls -hls_time 4 -hls_flags +delete_segments -hls_playlist_type event stream.m3u8

this is using hw accelaration, but when i observe the files, the bitrate is way to high ... the limit of 2k doesnt really apply, you may have an idea ?

**Comment by alturismo** [comment]
ok, i think i got it now, while vlc cant play it ... but hls stream works in browser ;)

hw accel looking ok, what is still using the most cpu is java ...
`Every 2.0s: ps aux | sort -nrk 3,3 | head -n 5                                                                                                                    b29b25bd1ae6: Wed Oct  7 10:57:27 2020

root         7 71.9  1.3 23765232 874736 ?     Sl   10:46   8:05 java -jar /app/proxyLive.jar
root       178  5.2  0.2 1175620 153000 ?      Sl   10:52   0:17 ffmpeg -hwaccel vaapi -vaapi_device /dev/dri/ren.....
root       176  0.1  0.0 186012 22932 ?        S    10:52   0:00 ffmpeg -i http://localhost:8080/view/v360p/8268cd9c3dc62......
root       397  0.0  0.0   4548   780 pts/0    S+   10:57   0:00 head -n 5
root       396  0.0  0.0  23312  1016 pts/0    S+   10:57   0:00 sort -nrk 3,3`

so i permanently have 1 jumping core to 100 % cpu load
![image](https://user-images.githubusercontent.com/8406490/95322530-f0a1fb80-089c-11eb-95f3-1b5392093b09.png)

may an idea if there is a solution about it ? getting java smoother ...
