### ISSUE TITLE
guide to build jar

### ISSUE THREAD

**Issue by astralink** [segator/proxylive#2]
build jar for ubuntu
git clone https://github.com/segator/proxylive.git
cd proxylive/
mvn compile

[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building ProxyLive 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[WARNING] The artifact org.apache.commons:commons-io:jar:1.3.2 has been relocated to commons-io:commons-io:jar:1.3.2
[INFO]
[INFO] --- maven-resources-plugin:2.7:resources (default-resources) @ ProxyLive ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] Copying 1 resource
[INFO] Copying 0 resource
[INFO]
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ ProxyLive ---
[INFO] Nothing to compile - all classes are up to date
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.538s
[INFO] Finished at: Sun Oct 29 23:43:27 CET 2017
[INFO] Final Memory: 14M/605M
[INFO] ------------------------------------------------------------------------

good luck

**Comment by astralink** [comment]
other try from centos
[root@CentOS-65-64-minimal proxylive]# docker build -t my_mongodb .
Sending build context to Docker daemon 288.8 kB
Sending build context to Docker daemon
Step 0 : FROM jrottenberg/ffmpeg:3.2-centos
3.2-centos: Pulling from jrottenberg/ffmpeg
6c5159923047: Layer already being pulled by another client. Waiting.
6c5159923047: Already exists
acec82331181: Pull complete
f519e1fde1a8: Pull complete
78eb6454c274: Pull complete
32e684e9ea98: Pull complete
2586cfa37939: Pull complete
b4d062cda1ee: Pull complete
fd37b440e8a1: Pull complete
358eea72dcad: Pull complete
Digest: sha256:6792de5be72b621ddc680661683ff76300b1a8281441ddf341a4c4b52805235e
Status: Downloaded newer image for jrottenberg/ffmpeg:3.2-centos
 ---> 358eea72dcad
Step 1 : MAINTAINER Isaac Aymerich <isaac.aymerich@gmail.com>
could not find image: no such id: 6c51599230478bde53cfcf5f4e7f68c2bf295102f31146c0bb6e9b814365c0e7

**Comment by segator** [comment]
Now you can compile directly the docker image

docker build -t image .
In fact I enabled the auto-build in hub.docker.com
