### ISSUE TITLE
error: RemoteException("channel no exist")

### ISSUE THREAD

**Issue by nileio** [segator/proxylive#3]
hi there, 
I recieve the following error when trying to connect to a channel using the url
http://username:password@tvheadendserver:8080/view/1080p/1478245957
1478245957 is a channelid from my tvheadendserver. I can successfully access the same channel using the usual tvheadend url which is
http://username:password@tvheadendserver:9981/stream/channelid/1478245957
note the url above contain the literal "channelid" not "channel" as in your examples and code.

here is the error:

> java.rmi.RemoteException: channel no exist
> 
> 	at com.github.segator.proxylive.controller.StreamController.getChannelData(StreamController.java:408) ~[classes!/:1.0-SNAPSHOT],
> 	at com.github.segator.proxylive.controller.StreamController.dispatchStream(StreamController.java:98) ~[classes!/:1.0-SNAPSHOT],
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_191],
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_191],
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_191],
> 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_191],
> 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) ~[spring-web-4.3.14.RELEASE.jar!/:4.3.14.RELEASE],
> 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-4.3.14.RELEASE.jar!/:4.3.14.RELEASE],
> 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) ~[spring-webmvc-4.3.14.RELEASE.jar!/:4.3.14.RELEASE]

please can you point me to the issue ?

**Comment by segator** [comment]
yes, you should use large tvheadend channel ID.
Anyway the m3u with all the channels is automatically generated
try to get the m3u like this yourserver/channel/list/mpeg/raw

**Comment by nileio** [comment]
thanks for quick response .. what has just worked is getting the playlist using the format you suggested in readme 

http://[server]:8080/channel/list/[format]/[profile]?user=clientUser&pass=clientPass

this downloaded an m3u8 playlist and the links worked !!

the m3u8 file contains all the links. I notice you use UUID not the channelid which is generated from the tvheadend playlist

**Comment by nileio** [comment]
@segator thanks for the application. i am trying to make use of the application so that I can prefetch channels in order to avoid client buffering. i am facing issues with continous buffering / stalls because of bitrate and network condition. I was looking for a solution where I can prefetch the requested channel in a big buffer so i can get a smooth client playback. I am happy to contribute code,etc. I just need to find the right starting point. 
I notice your buffers config in application.yml ... can I use those to address my needs ? do you suggest other ways / solutions ? 
any suggestions welcome!! thanks

**Comment by segator** [comment]
yes you can define large buffer. the buffer in fact is a circular Buffer,  but I dont think you get any benefit to have for example 500M buffer, if a client have connection issues and are not able to get sustained download speed in the end the user will get to the end of the buffer and the system automatically set his pointer to the start(so it will get a cut in the image).

The good point is proxylive allow transcoding so you can define multiple transcoding with diferent bitrates. In my default configuration you have transcoding that support mobile 3g connnections.

About contribute, I'm happy to hear that, anything you need you can question ;)

**Comment by nileio** [comment]
hi @segator - can you pls explain the method you use to build an HLS stream ? for example, if my stream is mpegts - how do you output an HLS instead ? for me it does not work. the channel url looks like 
http://server:port/view/1080p/f92c43b5cad3138320c0fd414e7aca20playlist.m3u8?user=username&pass=password

is this feature intended only for HLS streams ? or can it work on an http stream and create a local HLS stream.. not sure if my question makes sense. any information will be good .

**Comment by nileio** [comment]
@segator  thanks for reply. I tried both ways, and it does not work on both cases.
I recieved 404 error.
Question is : were you trying to build an HLS m3u8 playlist from an mpegts stream ? and vice versa ? or is it purely what the server should provide. My server does not provide HLS stream.
I guess you only implementing a proxy so i think the answer is that the server must be providing HLS stream. but like to confirm.
Thanks

**Comment by segator** [comment]
we use internally FFMpeg to build HLS so the tvheadend input is enough, the problem reside in the implementation I remember had some problems with HLS and probably I disabled it.

But I say the same, I need to rewrite the whole application, when you have lot of concurrency the process skip checking some inputs(by error) so the state finish inconsistent.

**Comment by segator** [comment]
In some days in going to upload a fix for hls,  the changes im doing works and also in chromecast,have to check on some smart tv.

**Comment by segator** [comment]
in the last commit HLS works, tested on chromecast, VLC, and samsung smartTV

**Comment by segator** [comment]
HLS is working in prod nicely. I close the issue
