### ISSUE TITLE
MPEGTS with MPTS transcode.

### ISSUE THREAD

**Issue by sachin0606** [segator/proxylive#4]
Hi, 

wanted to transcode the MPTS stream of MP4 to MP2 stream, how can i use this in windows and let me know way to install .

**Comment by segator** [comment]
I dont now how exactly works MP2 streams, if ffmpegTS allow to transcode to this format you can play,
with the profiles and new mpegTS.parameters.

if MP2 is like mpegTS(simple flow of data in a single connection) should works using the proxylive mpegTS transformer.

let me now if you finally get it work I will create a specific section for MP2

**Comment by segator** [comment]
any new?

**Comment by sachin0606** [comment]
I am not able to use this plugin. can you help me to use this in windows machine.

**Comment by segator** [comment]
This application is writen in java, it works on windows in fact i developed the app in windows.
What problem do you have?

**Comment by sachin0606** [comment]
how to setup the project and execute.

**Comment by segator** [comment]
Is documented on the readme, use docker or build yourself the project with mvn build

**Comment by sachin0606** [comment]
generated the jar file. but its not opening with java binary se executable. anything i am missing.

**Comment by segator** [comment]
Please show the runtine log here

**Comment by sachin0606** [comment]
how to get run time log. as i am unable to get that. here is my jar file. 
[Uploading ProxyLive.zip…]()

**Comment by segator** [comment]
I supose you dont have your config on consul right? Then disable it(bootrap.yml)

**Comment by segator** [comment]
Now Proxylive support MPTS and UDP Input
