### ISSUE TITLE
Input MPEG TS Multicast - Questions

### ISSUE THREAD

**Issue by Viox-LJ** [segator/proxylive#6]
Hi how are you? this is not a issue is more like a questions about the app works.
I have 100 channels in multicast from satellite receptor, now i have this channels over a 2 Wowza Servers, but need transcoding first and later the transcode put on Wowza to make the streaming online.

This is possible with this app?¿ what is the hardware limitation o what is the requirements i need to make transcoding the 100 channels?

Thx.
BR
Santiago

**Comment by segator** [comment]
Sorry I didn't saw your question.
The app happily can support 100 channels, but take in mind 2 considerations.

calculate that every channel opened can consume on RAM same as defined buffer size.
So probably you will need a large amount of ram.

you said about transcoding are you going to transcode 100 channels at the same time? This will require a masive amount of cpu. in This case if necesary I probably use multiple servers.

Anyway the idea of proxylive is do the transcoding on demand, I don't know if wowza is fetching channels on user demand or always persistent.
